# Blackjack Config File

# Server Config
server:
  sqlite_db_path: "./sql/schema"
  port: 42069
  git_client_id: ${GIT_CLIENT_ID}
  sqlite_db_name: ${SQLITE_DB}

log_level: INFO

table_action_timeout_seconds: 30
table_auto_delete_timeout_minutes: 5

# Game Config
stand_on_soft_17: true
bet_time_seconds: 30
deck_count: 6
cut_location: 150

# TUI Config
